### ISSUE TITLE
ScaleLLM Roadmap

### ISSUE THREAD

**Issue by guocuimi** [vectorch-ai/ScaleLLM#84]
We're excited to present the features we're currently working on and planning to support in this roadmap document. Your feedback is highly valued, so please don't hesitate to comment or reach out if you have anything you'd like to add or discuss. We're committed to delivering the best possible experience with ScaleLLM.

### Efficiency

- [x] Adding flash decoding with paged KV cache support [**Done**]
- [ ] Introducing attention kernel capable of supporting speculative decoding [**Ongoing**]
    - [ ] Exploring the feasibility of adopting the flashinfer library [**Ongoing**]
- [ ] Implementing speculative decoding [**Ongoing**]
- [ ] Enabling CUDA graph for decoding to improve performance [**Ongoing**]
- [ ] Implementing dynamic split-fuse for enhanced latency
- [ ] Exploring lookahead decoding support

### Cache

- [ ] Implementing stateful conversation to avoid recomputing for chat sessions

### New Models

- [ ] Integrating Google Gemma
- [ ] Incorporating the Mixtral MoE model
    - [ ] Implementing MoE (Mixture of Experts) kernels
- [ ] Introducing the Mamba model

### Usability

- [ ] Developing Python wrapper for easier integration [**Ongoing**]
- [ ] Enhancing documentation for improved usability

### Misc

- [ ] Conducting benchmarking to compare performance with other open-source projects

---
### Efficiency

- [ ] Implementing fused FFN (Feed-Forward Network) to enhance efficiency
- [ ] Introducing a ring attention mechanism for handling long contexts

### New Devices

- [ ] Adding support for Apple chips
- [ ] Exploring other chips such as TPU, NPU, etc.

### New Models

- [ ] Introducing multi-modal models
    - [ ] LLaVA model
- [ ] LoRA & QLoRA
    - [ ] [S-LoRA](https://github.com/S-LoRA/S-LoRA): Serving thousands of LoRA adapters

### New GPU Architecture

- [ ] Turing architecture (sm75)

### Structural Decoding

- [ ] Function Calling

### Quantization

- [ ] Supporting FP8 for both models and KV caches

### Supported Operating Systems

- [ ] Extending support to macOS and Windows platforms

### Misc

- [ ] Loosening coupling with PyTorch for easy deployment

**Comment by omarmhaimdat** [comment]
I think LLaMA 3 should be added as well, and probably should be high priority.

**Comment by guocuimi** [comment]
> I think LLaMA 3 should be added as well, and probably should be high priority.

Yes, Llama3 is supported already, please check latest release.
